### ISSUE TITLE
关于使用第三方域名的域名及域名解析问题

### ISSUE THREAD

**Issue by ouyanmao** [andyzhshg/syno-acme#1]
你好,如果是直接使用群晖申请的免费域名XXXXX.synology.me这种需要弄DNS解析吗?直接用这种是不是最简单的方案?
我看你申请了阿里云的域名及阿里云的DNS解析服务,我看到阿里云服务条款“com/.net/.cn/.xin/.top/.xyz/.vip/.club/.shop/.wang/.ren等域名注册成功后必须进行域名实名认证，否则域名会处于Serverhold状态，无法正常使用。查看详情 ” 我申请阿里云的域名的域名是不是要实名认证?
我没建站的经验,麻烦了.谢谢解答.

**Comment by wallex64** [comment]
我没有直接用群晖的免费域名，所以具体情况不太清楚，我估计直接用群晖的域名的话是不需要自己去搞证书的。
我的阿里云的域名是没有备案的，我印象中没有备案的域名是无法在阿里云自己的主机上使用80或者443端口，域名指向其他主机应该阿里控制不了。

**Comment by andyzhshg** [comment]
我没有直接用群晖的免费域名，所以具体情况不太清楚，我估计直接用群晖的域名的话是不需要自己去搞证书的。
我的阿里云的域名是没有备案的，我印象中没有备案的域名是无法在阿里云自己的主机上使用80或者443端口，域名指向其他主机应该阿里控制不了。

**Comment by ouyanmao** [comment]
请问你是购买哪种后缀的域名的?我想按照你的域名来买,避免二次折腾,已经奋斗3天,进度太慢.麻烦你了.谢谢

Walle x64 <notifications@github.com> 于 2018年7月2日周一 11:58写道：

**Comment by andyzhshg** [comment]
@ouyanmao 这里不适合讨论项目部相关的问题，你加我的telegram吧 `@carlzhang`

**Comment by ouyanmao** [comment]
刚申请了telegram,加你了.可以拉我进群吗.谢谢


ZHANG SHI GUANG <notifications@github.com> 于2018年7月3日周二 下午1:22写道：
