### ISSUE TITLE
自问自答：证书被自动重置，DSM6.x不支持ECC证书

### ISSUE THREAD

**Issue by UlaEve** [andyzhshg/syno-acme#105]
最近发现证书更新出问题了。排查脚本功能正常，生成成的证书也在有效期内，也按照正确的位置存放进去了。但是系统仍然会把默认证书替换掉我的自定义证书。排查发现，手动导入证书报错，提示：DSM不支持 ECC 证书。
修正方法：

Open your cert-up.sh script in a text editor.
Locate the line where acme.sh is called to issue a certificate. It might look similar to the example below:
```sh
${ACME_BIN_PATH}/acme.sh --issue ...
```
Add the --keylength parameter to specify the RSA key length. The modified line should look like this:
```sh
${ACME_BIN_PATH}/acme.sh --issue --keylength 4096 ...
```
After making this change, save the cert-up.sh script and run it to generate a new RSA certificate with the specified key length.

**Comment by Paris0-0** [comment]
感谢分享
