### ISSUE TITLE
如果update 非默认证书，是否脚本能支持？

### ISSUE THREAD

**Issue by ferocknew** [andyzhshg/syno-acme#12]
如题

**Comment by ferocknew** [comment]
fork 了一下
递交了一些修改。url 如下：
https://github.com/ferocknew/syno-acme/commit/0a47f7d9dede14a9180cd66b333b463a71b9ee75

还修复了一个zsh 下的bug，config 文件报错的问题。

**Comment by andyzhshg** [comment]
非主流需求可能会增加配置难度，暂不考虑支持
