### ISSUE TITLE
nameslio睡眠1天以上

### ISSUE THREAD

**Issue by ColeHou** [andyzhshg/syno-acme#16]
用了0.15之后请问怎么导入证书，证书里面还是只有群晖那一个

**Comment by ColeHou** [comment]
就是运行完脚本发现还是群晖那个证书，ca信息还是群晖的

**Comment by ColeHou** [comment]
```
begin update cert
------ begin updateCrt ------
begin backupCrt
done backupCrt
begin installAcme
begin downloading acme.sh tool...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    57  100    57    0     0     52      0  0:00:01  0:00:01 --:--:--    52
100    57  100    57    0     0     52      0  0:00:01  0:00:01 --:--:--    52
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
100   123    0   123    0     0     39      0 --:--:--  0:00:03 --:--:--    39

  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
curl: (52) Empty reply from server
tar (child): acme.sh.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
tar (child): acme.sh.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
begin installing acme.sh tool...
/volume1/auto_script/syno-acme-0.1.5/syno-acme-0.1.5/cert-up.sh: line 36: cd: HOME not set
/volume1/auto_script/syno-acme-0.1.5/syno-acme-0.1.5/cert-up.sh: line 37: ./acme.sh: No such file or directory
done installAcme
begin generateCrt
begin updating default cert by acme.sh tool
/volume1/auto_script/syno-acme-0.1.5/syno-acme-0.1.5/cert-up.sh: line 48: /volume1/auto_script/syno-acme-0.1.5/syno-acme-0.1.5/acme.sh/acme.sh.env: No such file or directory
/volume1/auto_script/syno-acme-0.1.5/syno-acme-0.1.5/cert-up.sh: line 49: /volume1/auto_script/syno-acme-0.1.5/syno-acme-0.1.5/acme.sh/acme.sh: No such file or directory
/volume1/auto_script/syno-acme-0.1.5/syno-acme-0.1.5/cert-up.sh: line 50: /volume1/auto_script/syno-acme-0.1.5/syno-acme-0.1.5/acme.sh/acme.sh: No such file or directory
/volume1/auto_script/syno-acme-0.1.5/syno-acme-0.1.5/cert-up.sh: line 54: cd: /volume1/auto_script/syno-acme-0.1.5/syno-acme-0.1.5/temp: No such file or directory
done generateCrt
begin updateService
cp cert path to des
/usr/syno/etc/certificate/_archive/dUKSqI/cert.pem /usr/syno/etc/certificate/smbftpd/ftpd/cert.pem
/usr/syno/etc/certificate/_archive/dUKSqI/privkey.pem /usr/syno/etc/certificate/smbftpd/ftpd/privkey.pem
/usr/syno/etc/certificate/_archive/dUKSqI/fullchain.pem /usr/syno/etc/certificate/smbftpd/ftpd/fullchain.pem
/usr/syno/etc/certificate/_archive/dUKSqI/cert.pem /usr/syno/etc/certificate/system/default/cert.pem
/usr/syno/etc/certificate/_archive/dUKSqI/privkey.pem /usr/syno/etc/certificate/system/default/privkey.pem
/usr/syno/etc/certificate/_archive/dUKSqI/fullchain.pem /usr/syno/etc/certificate/system/default/fullchain.pem
done updateService
begin reloadWebService
reloading new cert...
alias-register stop/waiting
done reloadWebService
------ end updateCrt ------
```

**Comment by andyzhshg** [comment]
看起来是下载`acme.sh`工具的时候失败了，请确认可以在nas上下载`https://github.com/Neilpang/acme.sh/archive/2.7.9.tar.gz`这个文件

**Comment by ColeHou** [comment]
> 看起来是下载`acme.sh`工具的时候失败了，请确认可以在nas上下载`https://github.com/Neilpang/acme.sh/archive/2.7.9.tar.gz`这个文件

好的，感谢，我手动下载到群晖上吧

**Comment by ColeHou** [comment]
> 看起来是下载`acme.sh`工具的时候失败了，请确认可以在nas上下载`https://github.com/Neilpang/acme.sh/archive/2.7.9.tar.gz`这个文件

```
[Wed Apr 17 18:14:16 CST 2019] xxxxx.com:Verify error:Incorrect TXT record 
[Wed Apr 17 18:14:16 CST 2019] Removing DNS records.
[Wed Apr 17 18:14:18 CST 2019] Successfully retrieved the record id for ACME challenge.
[Wed Apr 17 18:14:19 CST 2019] Successfully removed the TXT record.
[Wed Apr 17 18:14:22 CST 2019] Successfully retrieved the record id for ACME challenge.
[Wed Apr 17 18:14:23 CST 2019] Successfully removed the TXT record.
[Wed Apr 17 18:14:23 CST 2019] Please add '--debug' or '--log' to check more details.
[Wed Apr 17 18:14:23 CST 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Wed Apr 17 18:14:25 CST 2019] Installing cert to:/usr/syno/etc/certificate/_archive/dUKSqI/cert.pem
cat: /volume1/auto_script/syno-acme-0.1.5/syno-acme-0.1.5/acme.sh/xxxxx.com/xxxxx.com.cer: No such file or directory
```

**Comment by andyzhshg** [comment]
> > 看起来是下载`acme.sh`工具的时候失败了，请确认可以在nas上下载`https://github.com/Neilpang/acme.sh/archive/2.7.9.tar.gz`这个文件
> 
> ```
> [Wed Apr 17 18:14:16 CST 2019] xxxxx.com:Verify error:Incorrect TXT record 
> [Wed Apr 17 18:14:16 CST 2019] Removing DNS records.
> [Wed Apr 17 18:14:18 CST 2019] Successfully retrieved the record id for ACME challenge.
> [Wed Apr 17 18:14:19 CST 2019] Successfully removed the TXT record.
> [Wed Apr 17 18:14:22 CST 2019] Successfully retrieved the record id for ACME challenge.
> [Wed Apr 17 18:14:23 CST 2019] Successfully removed the TXT record.
> [Wed Apr 17 18:14:23 CST 2019] Please add '--debug' or '--log' to check more details.
> [Wed Apr 17 18:14:23 CST 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
> [Wed Apr 17 18:14:25 CST 2019] Installing cert to:/usr/syno/etc/certificate/_archive/dUKSqI/cert.pem
> cat: /volume1/auto_script/syno-acme-0.1.5/syno-acme-0.1.5/acme.sh/xxxxx.com/xxxxx.com.cer: No such file or directory
> ```
> 域名是nameslio的。。。TXT一直失败

有在配置文件里添加`nameslio`的`key`吗，还有就是尝试把配置文件中的`DNS_SLEEP `调大试一下

**Comment by ColeHou** [comment]
> > > 看起来是下载`acme.sh`工具的时候失败了，请确认可以在nas上下载`https://github.com/Neilpang/acme.sh/archive/2.7.9.tar.gz`这个文件
> > 
> > 
> > ```
> > [Wed Apr 17 18:14:16 CST 2019] xxxxx.com:Verify error:Incorrect TXT record 
> > [Wed Apr 17 18:14:16 CST 2019] Removing DNS records.
> > [Wed Apr 17 18:14:18 CST 2019] Successfully retrieved the record id for ACME challenge.
> > [Wed Apr 17 18:14:19 CST 2019] Successfully removed the TXT record.
> > [Wed Apr 17 18:14:22 CST 2019] Successfully retrieved the record id for ACME challenge.
> > [Wed Apr 17 18:14:23 CST 2019] Successfully removed the TXT record.
> > [Wed Apr 17 18:14:23 CST 2019] Please add '--debug' or '--log' to check more details.
> > [Wed Apr 17 18:14:23 CST 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
> > [Wed Apr 17 18:14:25 CST 2019] Installing cert to:/usr/syno/etc/certificate/_archive/dUKSqI/cert.pem
> > cat: /volume1/auto_script/syno-acme-0.1.5/syno-acme-0.1.5/acme.sh/xxxxx.com/xxxxx.com.cer: No such file or directory
> > ```
> > 域名是nameslio的。。。TXT一直失败
> 
> 有在配置文件里添加`nameslio`的`key`吗，还有就是尝试把配置文件中的`DNS_SLEEP `调大试一下

我都做了，sleep我休眠了7250秒，2个多小时，key也加了，到key的哪一步都是争取的，显示添加了txt的记录，但是没有解析程序，我尝试睡眠一天之后再试试吧

**Comment by ColeHou** [comment]
已解决，nameslio睡眠1天以上才行
