### ISSUE TITLE
vpn套件的证书不会自动更新

### ISSUE THREAD

**Issue by kuailezhiyuan** [andyzhshg/syno-acme#19]
vpn套件的证书不会自动更新，有什么办法让他自动更新吗？

**Comment by andyzhshg** [comment]
我这里没有用到VPN套件，如果可能的话，能否提供一下VPN套件安装后证书的所在路径？

**Comment by kuailezhiyuan** [comment]
不好意思，我也没有找到VPN套件的证书位置。我不太清楚群辉套件的安装位置

**Comment by andyzhshg** [comment]
> 不好意思，我也没有找到VPN套件的证书位置。我不太清楚群辉套件的安装位置

请尝试更新下0.1.7版本，看看问题是否已经修复

**Comment by kuailezhiyuan** [comment]
我更新了脚本，然后还是不行，我用了一晚上的时间找到了openvpn的启动脚本，发现里面每次运行openvpn的时候会把脚本从安装目录复制到一个指定目录
PKG_USERCONF_DIR="/usr/syno/etc/packages/VPNCenter"
`        # copy certificate : ca.crt, ca_bundle.crt, server.crt, and server.key of ssl
	/bin/rm -f ${PKG_TARGET}/etc/openvpn/keys/ca.crt
	/bin/rm -f ${PKG_TARGET}/etc/openvpn/keys/ca_bundle.crt
	/bin/cp -f ${PKG_USERCONF_DIR}/openvpn/keys/ca.crt ${PKG_TARGET}/etc/openvpn/keys/
	/bin/cp -f ${PKG_USERCONF_DIR}/openvpn/keys/ca_bundle.crt ${PKG_TARGET}/etc/openvpn/keys/
	/bin/cp -f ${PKG_USERCONF_DIR}/openvpn/keys/server.crt ${PKG_TARGET}/etc/openvpn/keys/
	/bin/cp -f ${PKG_USERCONF_DIR}/openvpn/keys/server.key ${PKG_TARGET}/etc/openvpn/keys/`
启动和关闭openvpn的脚本是
`/var/packages/VPNCenter/target/scripts/openvpn.sh start|stop`
我还没来及进行测试（我暂时也不知道如何测试openvpn的证书是否自动更换），希望这些能帮助你。

**Comment by andyzhshg** [comment]
感谢 @binalloy 的 pr #31 ，此问题已修复。
