### ISSUE TITLE
[warn]: cp cert path to des 

### ISSUE THREAD

**Issue by mrguangtu** [andyzhshg/syno-acme#2]
一切顺利的用到了您的功能，感谢您帮我节约了时间！

log中发现warn，code如下。大概是拷贝文件的时候出错。虽然不影响啥，但看起来还是有些紧张，不知是什么原因，issue一下请知晓~~

再次感谢您的script！

`begin updateService
cp cert path to des
/usr/syno/etc/certificate/_archive/VOiN2y/cert.pem /usr/syno/etc/certificate/SynologyFileManager/SynologyFileManager/cert.pem
[WRN] copy from /usr/syno/etc/certificate/_archive/VOiN2y/cert.pem to /usr/syno/etc/certificate/SynologyFileManager/SynologyFileManager/cert.pem fail
/usr/syno/etc/certificate/_archive/VOiN2y/privkey.pem /usr/syno/etc/certificate/SynologyFileManager/SynologyFileManager/privkey.pem
[WRN] copy from /usr/syno/etc/certificate/_archive/VOiN2y/privkey.pem to /usr/syno/etc/certificate/SynologyFileManager/SynologyFileManager/privkey.pem fail
/usr/syno/etc/certificate/_archive/VOiN2y/fullchain.pem /usr/syno/etc/certificate/SynologyFileManager/SynologyFileManager/fullchain.pem
[WRN] copy from /usr/syno/etc/certificate/_archive/VOiN2y/fullchain.pem to /usr/syno/etc/certificate/SynologyFileManager/SynologyFileManager/fullchain.pem fail
/usr/syno/etc/certificate/_archive/VOiN2y/cert.pem /usr/syno/etc/certificate/smbftpd/ftpd/cert.pem
/usr/syno/etc/certificate/_archive/VOiN2y/privkey.pem /usr/syno/etc/certificate/smbftpd/ftpd/privkey.pem
/usr/syno/etc/certificate/_archive/VOiN2y/fullchain.pem /usr/syno/etc/certificate/smbftpd/ftpd/fullchain.pem
/usr/syno/etc/certificate/_archive/VOiN2y/cert.pem /usr/syno/etc/certificate/system/default/cert.pem
/usr/syno/etc/certificate/_archive/VOiN2y/privkey.pem /usr/syno/etc/certificate/system/default/privkey.pem
/usr/syno/etc/certificate/_archive/VOiN2y/fullchain.pem /usr/syno/etc/certificate/system/default/fullchain.pem
/usr/syno/etc/certificate/_archive/VOiN2y/cert.pem /usr/syno/etc/certificate/VPNCenter/OpenVPN/cert.pem
[WRN] copy from /usr/syno/etc/certificate/_archive/VOiN2y/cert.pem to /usr/syno/etc/certificate/VPNCenter/OpenVPN/cert.pem fail
/usr/syno/etc/certificate/_archive/VOiN2y/privkey.pem /usr/syno/etc/certificate/VPNCenter/OpenVPN/privkey.pem
[WRN] copy from /usr/syno/etc/certificate/_archive/VOiN2y/privkey.pem to /usr/syno/etc/certificate/VPNCenter/OpenVPN/privkey.pem fail
/usr/syno/etc/certificate/_archive/VOiN2y/fullchain.pem /usr/syno/etc/certificate/VPNCenter/OpenVPN/fullchain.pem
[WRN] copy from /usr/syno/etc/certificate/_archive/VOiN2y/fullchain.pem to /usr/syno/etc/certificate/VPNCenter/OpenVPN/fullchain.pem fail
/usr/syno/etc/certificate/_archive/VOiN2y/cert.pem /usr/syno/etc/certificate/LogCenter/pkg-LogCenter/cert.pem
[WRN] copy from /usr/syno/etc/certificate/_archive/VOiN2y/cert.pem to /usr/syno/etc/certificate/LogCenter/pkg-LogCenter/cert.pem fail
/usr/syno/etc/certificate/_archive/VOiN2y/privkey.pem /usr/syno/etc/certificate/LogCenter/pkg-LogCenter/privkey.pem
[WRN] copy from /usr/syno/etc/certificate/_archive/VOiN2y/privkey.pem to /usr/syno/etc/certificate/LogCenter/pkg-LogCenter/privkey.pem fail
/usr/syno/etc/certificate/_archive/VOiN2y/fullchain.pem /usr/syno/etc/certificate/LogCenter/pkg-LogCenter/fullchain.pem
[WRN] copy from /usr/syno/etc/certificate/_archive/VOiN2y/fullchain.pem to /usr/syno/etc/certificate/LogCenter/pkg-LogCenter/fullchain.pem fail
/usr/syno/etc/certificate/_archive/VOiN2y/cert.pem /usr/syno/etc/certificate/SynologyDrive/SynologyDrive/cert.pem
[WRN] copy from /usr/syno/etc/certificate/_archive/VOiN2y/cert.pem to /usr/syno/etc/certificate/SynologyDrive/SynologyDrive/cert.pem fail
/usr/syno/etc/certificate/_archive/VOiN2y/privkey.pem /usr/syno/etc/certificate/SynologyDrive/SynologyDrive/privkey.pem
[WRN] copy from /usr/syno/etc/certificate/_archive/VOiN2y/privkey.pem to /usr/syno/etc/certificate/SynologyDrive/SynologyDrive/privkey.pem fail
/usr/syno/etc/certificate/_archive/VOiN2y/fullchain.pem /usr/syno/etc/certificate/SynologyDrive/SynologyDrive/fullchain.pem
[WRN] copy from /usr/syno/etc/certificate/_archive/VOiN2y/fullchain.pem to /usr/syno/etc/certificate/SynologyDrive/SynologyDrive/fullchain.pem fail
done updateService`

**Comment by mrguangtu** [comment]
检查了一下，可能是certivicate下面目录不存在导致的，例如没有SynologyDrive、VPNCenter、LogCenter之类的目录导致的。

**Comment by HugoPresents** [comment]
我也遇到一个 SynologyDrive 的 WARN 估计是没有给这些服务开独立端口，所以不需要额外配置证书吧，现在用起来没什么问题

**Comment by andyzhshg** [comment]
warning对使用没有影响，新版本已经去除了这种无用的warning[https://github.com/andyzhshg/syno-acme/releases/tag/v0.1.5](https://github.com/andyzhshg/syno-acme/releases/tag/v0.1.5)
