### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by jonntd** [andyzhshg/syno-acme#23]
[Thu Jul 25 12:57:23 CST 2019] Good, bash is found, so change the shebang to use bash as preferred.
[Thu Jul 25 12:57:25 CST 2019] OK
done installAcme
begin generateCrt
begin updating default cert by acme.sh tool
[Thu Jul 25 12:57:25 CST 2019] Unknown parameter : 
[Thu Jul 25 12:57:25 CST 2019] '-d' is not a valid domain for parameter '-d'
/volume1/web/acme/cert-up.sh: line 54: cd: /volume1/web/acme/temp/acme.sh-2.8.1: No such file or directory
done generateCrt
begin updateService
cp cert path to des

**Comment by andyzhshg** [comment]
已修复，请更新最新版本0.1.7。
