### ISSUE TITLE
请问能不能自动处理一下每次更新的时候把key和cert打包成p12

### ISSUE THREAD

**Issue by w0330t** [andyzhshg/syno-acme#24]
我群晖里装了个plex，让我提供p12……我想直接把路径写过去
![image](https://user-images.githubusercontent.com/4970238/63363708-add64900-c3a6-11e9-911c-6469fc57c8b5.png)

**Comment by KurisuWong** [comment]
用Reverse Proxy吧
控制台 -> 應用程序入口 -> 反向代理伺服器

**Comment by w0330t** [comment]
not work， 反向代理设置之后依然使用的Plex的证书而不是我的。

**Comment by w0330t** [comment]
能用，感谢~~

**Comment by bao3** [comment]
@w0330t 求教如何设置的，我对这个不是很精通，虽然知道反向代理，但是不确定怎么设置。

**Comment by w0330t** [comment]
[image: image.png]
这是我的设置，
[image: image.png]
这是我的路由器端口转发的配置
简单来说就是32400是应用本身的端口，然后我用群晖把这个端口反向代理到了32500端口，这时你在内网访问的端口就是32500，然后我又在路由器上把端口改访问改成了32400，
从公网IP访问过去就是访问32400，外表看上去没啥变化，然而……

Tyrael Wang <notifications@github.com> 于2019年9月16日周一 下午11:10写道：
