### ISSUE TITLE
证书频度达到Let's Encrypt上限会造成Synology证书管理页面被清空的bug

### ISSUE THREAD

**Issue by KurisuWong** [andyzhshg/syno-acme#26]
如果域名申请证书频度已经达到Let's Encrypt上限，一张空白的证书cert.pem会照样被复制，造成证书管理页面被清空的bug
![a](https://user-images.githubusercontent.com/15049035/64174643-48955400-ce8c-11e9-9961-0aa6255bcc0f.png)
![b](https://user-images.githubusercontent.com/15049035/64174645-48955400-ce8c-11e9-9d88-855219db0cc0.png)
![c](https://user-images.githubusercontent.com/15049035/64174646-492dea80-ce8c-11e9-9a99-68d99c0070d4.png)
![d](https://user-images.githubusercontent.com/15049035/64174647-492dea80-ce8c-11e9-92fc-3eff51e73f16.png)

解決这bug的方法是执行回滚命令
> /volume1/nas_share/certs/syno-acme/cert-up.sh revert

**Comment by KurisuWong** [comment]
I have already fixed the issue
Please check out the pull request https://github.com/andyzhshg/syno-acme/pull/27

**Comment by andyzhshg** [comment]
fixed on pr #28
