### ISSUE TITLE
acme 错误

### ISSUE THREAD

**Issue by gui-li** [andyzhshg/syno-acme#34]
当我第一次在执行cert-up.sh update 的时候，出现如下报错：

begin installing acme.sh tool...
cert-up.sh: line 39: ./acme.sh: No such file or directory
done installAcme
begin generateCrt
begin updating default cert by acme.sh tool
[Sat Dec 28 21:06:54 CST 2019] Please refer to https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html for error code: 4
[Sat Dec 28 21:06:54 CST 2019] Can not init api.

**Comment by andyzhshg** [comment]
怀疑是下载安装acme的步骤失败，请尝试重新运行脚本

**Comment by vc5** [comment]
已修复，参见https://github.com/andyzhshg/syno-acme/pull/41#issue-388133564

**Comment by andyzhshg** [comment]
close，thanks to @vc5
