### ISSUE TITLE
请问开启了Webdav服务，是否需要向/usr/local/etc/certificate目录下单独复制一份新证书

### ISSUE THREAD

**Issue by chenxiccc** [andyzhshg/syno-acme#38]
你好，我是在VPS上自动通过acme更新证书，并通过renew -hook在更新后自动同步到群晖。
参考你的脚本，获益匪浅，非常感谢。

有一个疑问：
我在群晖上开启了WebDav服务，观察/usr/local/etc/certificate目录下的目录为/WebDAVServer/webdav/，其下为我设置为默认的证书文件。
那么：
新证书我复制到/usr/syno/etc/certificate/_archive/xxxx 目录下就够了，复制后它会自己同步到/usr/local/etc/certificate的对应目录下，还是需要手工在/usr/local/etc/certificate目录下也复制一份？

以上，盼您解答，谢谢！

**Comment by andyzhshg** [comment]
请参考这个文件，[https://github.com/andyzhshg/syno-acme/blob/master/crt_cp.py](https://github.com/andyzhshg/syno-acme/blob/master/crt_cp.py)，根据 @pikachullk 的提交的修改可知，在文件 /usr/syno/etc/certificate/INFO 这个文件中，凡是字段 `isPkg` 为 `true` 的服务，可以认为是使用的套件证书，其对应的证书地址在 /usr/local/etc/certificate。
希望这个能有所帮助。
