### ISSUE TITLE
执行失败，提示没有config

### ISSUE THREAD

**Issue by WeiYang1982** [andyzhshg/syno-acme#40]
```
+ echo 'done installAcme'
done installAcme
+ rm -rf /volume1/docker/SSL_sh/temp
+ return 0
+ generateCrt
+ echo 'begin generateCrt'
begin generateCrt
+ cd /volume1/docker/SSL_sh
+ source config
cert-up.sh: line 49: source: config: file not found
```

但是目录下是有这个文件的
```
root@DS918plus:/volume1/docker/SSL_sh# ll
total 28

drwxr-xr-x+ 1 root       root    148 Mar 10 20:08 ..
drwx------  1 root       root     96 Mar 11 08:38 acme.sh
-rwxr-xr-x+ 1 root       root     57 Oct 21 16:38 acme.sh.address
drwxr-xr-x+ 1 root       root    264 Mar 11 08:38 backup
-rwxr-xr-x  1 root       root   3404 Mar 11 08:38 cert-up.sh
-rw-r--r--  1 root       root  12288 Mar 11 08:38 .cert-up.sh.swp
-rwxr-xr-x+ 1 root       root    776 Mar 10 20:44 config
-rwxr-xr-x+ 1 root       root   1182 Oct 21 16:38 crt_cp.py
```
请问这是怎么回事呢？

**Comment by RickGanKL** [comment]
我也有这个问题，请帮忙修复下。

**Comment by andyzhshg** [comment]
@WeiYang1982 @RickGanKL 能否提供下更详细的信息？

1. 运行的方式是什么？任务计划还是直接从shell执行的
2. 如果是直接从shell执行，运行的shell环境是什么？sh? bash? zsh?
3.  能够提供下更完整的配置文件（注意屏蔽隐私信息）或者日志

**Comment by RickGanKL** [comment]
@andyzhshg 非常感谢你的syno-acme。我已经使用了两年了。
1. 运行方式您教程里面syno的任务计划里面
2. shell环境是sh
3.配置文件和日志，请查看附件。

对了， DNS=dns_dp 但是，dns text记录实际上没有更新。APIKEY确定没有问题。

谢谢。
[log.zip](https://github.com/andyzhshg/syno-acme/files/4425085/log.zip)

**Comment by WeiYang1982** [comment]
> @WeiYang1982 @RickGanKL 能否提供下更详细的信息？
> 
> 1. 运行的方式是什么？任务计划还是直接从shell执行的
> 2. 如果是直接从shell执行，运行的shell环境是什么？sh? bash? zsh?
> 3. 能够提供下更完整的配置文件（注意屏蔽隐私信息）或者日志

Hi, 我在命令行用sh -x cert-up.sh update(root用户)执行和在计划任务里执行(root用户)，都是同样的提示
log config麻烦看附件
[log.zip](https://github.com/andyzhshg/syno-acme/files/4469370/log.zip)

**Comment by andyzhshg** [comment]
如 @RickGanKL 所说，应该是DNSPOD特有的问题，具体是DNSPOD的问题还是acme.sh的问题我还暂时定位不了。可以暂时将域名切换到其他服务商解析。

我暂时提供了一个新的分支版本，采用的acme.sh的开发版本，可以暂时解决这个问题：

[https://github.com/andyzhshg/syno-acme/releases/tag/v0.2.1-dnspod](https://github.com/andyzhshg/syno-acme/releases/tag/v0.2.1-dnspod)
