### ISSUE TITLE
问题:No such file or directory 

### ISSUE THREAD

**Issue by eiloogs** [andyzhshg/syno-acme#45]
begin update cert
------ begin updateCrt ------
begin backupCrt
done backupCrt
begin installAcme
begin downloading acme.sh tool...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve: cdn.jsdelivr.net (Could not contact DNS servers)
curl: no URL specified!
curl: try 'curl --help' for more information
tar (child): acme.sh.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
tar (child): acme.sh.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
begin installing acme.sh tool...
/volume1/system/syno-acme/cert-up.sh: line 39: ./acme.sh: No such file or directory
done installAcme
begin generateCrt
begin updating default cert by acme.sh tool
/volume1/system/syno-acme/cert-up.sh: line 50: /volume1/system/syno-acme/acme.sh/acme.sh.env: No such file or directory
/volume1/system/syno-acme/cert-up.sh: line 51: /volume1/system/syno-acme/acme.sh/acme.sh: No such file or directory
/volume1/system/syno-acme/cert-up.sh: line 52: /volume1/system/syno-acme/acme.sh/acme.sh: No such file or directory
done generateCrt
begin updateService
cp cert path to des
Copy cert for FTPS
Copy cert for DSM Desktop Service
Copy cert for WebDAVServer
done updateService
begin reloadWebService
reloading new cert...
alias-register stop/waiting
relading Apache 2.2
stop: Unknown job: pkg-apache22
start: Unknown job: pkg-apache22
reload: Unknown job: pkg-apache22
done reloadWebService
------ end updateCrt ------

**Comment by eiloogs** [comment]
老哥，这个问题出现好几次，没看懂啊- -

**Comment by eiloogs** [comment]
dns问题，结束

**Comment by busyhe** [comment]
@eiloogs 怎么解决的，我也是文件下载不下来

**Comment by eiloogs** [comment]
> @eiloogs怎么解决的，我也是文件下载不下来

我之前路由上设置的dns是本地网关，改成114的，重新联网 就阔以了，我是这样解决的。
