### ISSUE TITLE
脚本执行结束，证书并没有更换。

### ISSUE THREAD

**Issue by eiloogs** [andyzhshg/syno-acme#46]
begin update cert
------ begin updateCrt ------
begin backupCrt
done backupCrt
begin installAcme
begin downloading acme.sh tool...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    64  100    64    0     0    737      0 --:--:-- --:--:-- --:--:--   744
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   130  100   130    0     0    113      0  0:00:01  0:00:01 --:--:--   113

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 21105    0 21105    0     0   8396      0 --:--:--  0:00:02 --:--:-- 25427
100 43124    0 43124    0     0  12244      0 --:--:--  0:00:03 --:--:-- 23449
100 81962    0 81962    0     0  18659      0 --:--:--  0:00:04 --:--:-- 30255
100  128k    0  128k    0     0  24271      0 --:--:--  0:00:05 --:--:-- 35237
100  160k    0  160k    0     0  24566      0 --:--:--  0:00:06 --:--:-- 32851
100  172k    0  172k    0     0  25672      0 --:--:--  0:00:06 --:--:-- 35599
acme.sh-2.8.5/
acme.sh-2.8.5/.github/
acme.sh-2.8.5/.github/FUNDING.yml
acme.sh-2.8.5/.github/ISSUE_TEMPLATE.md
acme.sh-2.8.5/.github/PULL_REQUEST_TEMPLATE.md
acme.sh-2.8.5/.travis.yml
acme.sh-2.8.5/Dockerfile
acme.sh-2.8.5/LICENSE.md
acme.sh-2.8.5/README.md
acme.sh-2.8.5/acme.sh
acme.sh-2.8.5/deploy/
acme.sh-2.8.5/deploy/README.md
acme.sh-2.8.5/deploy/apache.sh
acme.sh-2.8.5/deploy/cpanel_uapi.sh
acme.sh-2.8.5/deploy/docker.sh
acme.sh-2.8.5/deploy/dovecot.sh
acme.sh-2.8.5/deploy/exim4.sh
acme.sh-2.8.5/deploy/fritzbox.sh
acme.sh-2.8.5/deploy/gcore_cdn.sh
acme.sh-2.8.5/deploy/gitlab.sh
acme.sh-2.8.5/deploy/haproxy.sh
acme.sh-2.8.5/deploy/keychain.sh
acme.sh-2.8.5/deploy/kong.sh
acme.sh-2.8.5/deploy/mailcow.sh
acme.sh-2.8.5/deploy/myapi.sh
acme.sh-2.8.5/deploy/mydevil.sh
acme.sh-2.8.5/deploy/mysqld.sh
acme.sh-2.8.5/deploy/nginx.sh
acme.sh-2.8.5/deploy/opensshd.sh
acme.sh-2.8.5/deploy/pureftpd.sh
acme.sh-2.8.5/deploy/qiniu.sh
acme.sh-2.8.5/deploy/routeros.sh
acme.sh-2.8.5/deploy/ssh.sh
acme.sh-2.8.5/deploy/strongswan.sh
acme.sh-2.8.5/deploy/unifi.sh
acme.sh-2.8.5/deploy/vault_cli.sh
acme.sh-2.8.5/deploy/vsftpd.sh
acme.sh-2.8.5/dnsapi/
acme.sh-2.8.5/dnsapi/README.md
acme.sh-2.8.5/dnsapi/dns_acmedns.sh
acme.sh-2.8.5/dnsapi/dns_acmeproxy.sh
acme.sh-2.8.5/dnsapi/dns_active24.sh
acme.sh-2.8.5/dnsapi/dns_ad.sh
acme.sh-2.8.5/dnsapi/dns_ali.sh
acme.sh-2.8.5/dnsapi/dns_autodns.sh
acme.sh-2.8.5/dnsapi/dns_aws.sh
acme.sh-2.8.5/dnsapi/dns_azure.sh
acme.sh-2.8.5/dnsapi/dns_cf.sh
acme.sh-2.8.5/dnsapi/dns_cloudns.sh
acme.sh-2.8.5/dnsapi/dns_cn.sh
acme.sh-2.8.5/dnsapi/dns_conoha.sh
acme.sh-2.8.5/dnsapi/dns_cx.sh
acme.sh-2.8.5/dnsapi/dns_cyon.sh
acme.sh-2.8.5/dnsapi/dns_da.sh
acme.sh-2.8.5/dnsapi/dns_ddnss.sh
acme.sh-2.8.5/dnsapi/dns_desec.sh
acme.sh-2.8.5/dnsapi/dns_dgon.sh
acme.sh-2.8.5/dnsapi/dns_dnsimple.sh
acme.sh-2.8.5/dnsapi/dns_do.sh
acme.sh-2.8.5/dnsapi/dns_doapi.sh
acme.sh-2.8.5/dnsapi/dns_domeneshop.sh
acme.sh-2.8.5/dnsapi/dns_dp.sh
acme.sh-2.8.5/dnsapi/dns_dpi.sh
acme.sh-2.8.5/dnsapi/dns_dreamhost.sh
acme.sh-2.8.5/dnsapi/dns_duckdns.sh
acme.sh-2.8.5/dnsapi/dns_durabledns.sh
acme.sh-2.8.5/dnsapi/dns_dyn.sh
acme.sh-2.8.5/dnsapi/dns_dynu.sh
acme.sh-2.8.5/dnsapi/dns_easydns.sh
acme.sh-2.8.5/dnsapi/dns_euserv.sh
acme.sh-2.8.5/dnsapi/dns_exoscale.sh
acme.sh-2.8.5/dnsapi/dns_freedns.sh
acme.sh-2.8.5/dnsapi/dns_gandi_livedns.sh
acme.sh-2.8.5/dnsapi/dns_gcloud.sh
acme.sh-2.8.5/dnsapi/dns_gd.sh
acme.sh-2.8.5/dnsapi/dns_gdnsdk.sh
acme.sh-2.8.5/dnsapi/dns_he.sh
acme.sh-2.8.5/dnsapi/dns_hexonet.sh
acme.sh-2.8.5/dnsapi/dns_hostingde.sh
acme.sh-2.8.5/dnsapi/dns_infoblox.sh
acme.sh-2.8.5/dnsapi/dns_internetbs.sh
acme.sh-2.8.5/dnsapi/dns_inwx.sh
acme.sh-2.8.5/dnsapi/dns_ispconfig.sh
acme.sh-2.8.5/dnsapi/dns_jd.sh
acme.sh-2.8.5/dnsapi/dns_kinghost.sh
acme.sh-2.8.5/dnsapi/dns_knot.sh
acme.sh-2.8.5/dnsapi/dns_leaseweb.sh
acme.sh-2.8.5/dnsapi/dns_lexicon.sh
acme.sh-2.8.5/dnsapi/dns_linode.sh
acme.sh-2.8.5/dnsapi/dns_linode_v4.sh
acme.sh-2.8.5/dnsapi/dns_loopia.sh
acme.sh-2.8.5/dnsapi/dns_lua.sh
acme.sh-2.8.5/dnsapi/dns_maradns.sh
acme.sh-2.8.5/dnsapi/dns_me.sh
acme.sh-2.8.5/dnsapi/dns_miab.sh
acme.sh-2.8.5/dnsapi/dns_misaka.sh
acme.sh-2.8.5/dnsapi/dns_myapi.sh
acme.sh-2.8.5/dnsapi/dns_mydevil.sh
acme.sh-2.8.5/dnsapi/dns_mydnsjp.sh
acme.sh-2.8.5/dnsapi/dns_namecheap.sh
acme.sh-2.8.5/dnsapi/dns_namecom.sh
acme.sh-2.8.5/dnsapi/dns_namesilo.sh
acme.sh-2.8.5/dnsapi/dns_nederhost.sh
acme.sh-2.8.5/dnsapi/dns_neodigit.sh
acme.sh-2.8.5/dnsapi/dns_netcup.sh
acme.sh-2.8.5/dnsapi/dns_nic.sh
acme.sh-2.8.5/dnsapi/dns_nsd.sh
acme.sh-2.8.5/dnsapi/dns_nsone.sh
acme.sh-2.8.5/dnsapi/dns_nsupdate.sh
acme.sh-2.8.5/dnsapi/dns_nw.sh
acme.sh-2.8.5/dnsapi/dns_one.sh
acme.sh-2.8.5/dnsapi/dns_online.sh
acme.sh-2.8.5/dnsapi/dns_openprovider.sh
acme.sh-2.8.5/dnsapi/dns_ovh.sh
acme.sh-2.8.5/dnsapi/dns_pdns.sh
acme.sh-2.8.5/dnsapi/dns_pleskxml.sh
acme.sh-2.8.5/dnsapi/dns_pointhq.sh
acme.sh-2.8.5/dnsapi/dns_rackspace.sh
acme.sh-2.8.5/dnsapi/dns_rcode0.sh
acme.sh-2.8.5/dnsapi/dns_regru.sh
acme.sh-2.8.5/dnsapi/dns_schlundtech.sh
acme.sh-2.8.5/dnsapi/dns_selectel.sh
acme.sh-2.8.5/dnsapi/dns_servercow.sh
acme.sh-2.8.5/dnsapi/dns_tele3.sh
acme.sh-2.8.5/dnsapi/dns_ultra.sh
acme.sh-2.8.5/dnsapi/dns_unoeuro.sh
acme.sh-2.8.5/dnsapi/dns_variomedia.sh
acme.sh-2.8.5/dnsapi/dns_vscale.sh
acme.sh-2.8.5/dnsapi/dns_vultr.sh
acme.sh-2.8.5/dnsapi/dns_yandex.sh
acme.sh-2.8.5/dnsapi/dns_zilore.sh
acme.sh-2.8.5/dnsapi/dns_zone.sh
acme.sh-2.8.5/dnsapi/dns_zonomi.sh
acme.sh-2.8.5/notify/
acme.sh-2.8.5/notify/dingtalk.sh
acme.sh-2.8.5/notify/ifttt.sh
acme.sh-2.8.5/notify/mail.sh
acme.sh-2.8.5/notify/mailgun.sh
acme.sh-2.8.5/notify/pop.sh
acme.sh-2.8.5/notify/postmark.sh
acme.sh-2.8.5/notify/pushover.sh
acme.sh-2.8.5/notify/sendgrid.sh
acme.sh-2.8.5/notify/slack.sh
acme.sh-2.8.5/notify/smtp.sh
acme.sh-2.8.5/notify/xmpp.sh
begin installing acme.sh tool...
[Sat Apr 11 09:41:50 CST 2020] It is recommended to install socat first.
[Sat Apr 11 09:41:50 CST 2020] We use socat for standalone server if you use standalone mode.
[Sat Apr 11 09:41:51 CST 2020] If you don't use standalone mode, just ignore this warning.
[Sat Apr 11 09:41:51 CST 2020] Installing to /volume1/system/syno-acme/acme.sh
[Sat Apr 11 09:41:51 CST 2020] Installed to /volume1/system/syno-acme/acme.sh/acme.sh
[Sat Apr 11 09:41:51 CST 2020] Installing alias to '/root/.profile'
[Sat Apr 11 09:41:51 CST 2020] OK, Close and reopen your terminal to start using acme.sh
[Sat Apr 11 09:41:51 CST 2020] Good, bash is found, so change the shebang to use bash as preferred.
[Sat Apr 11 09:41:52 CST 2020] OK
done installAcme
begin generateCrt
begin updating default cert by acme.sh tool
[Sat Apr 11 09:41:53 CST 2020] Multi domain='DNS:*.leee.fun,DNS:*.*.leee.fun'
[Sat Apr 11 09:41:53 CST 2020] Getting domain auth token for each domain
[Sat Apr 11 09:41:55 CST 2020] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rejectedIdentifier",
  "detail": "Error creating new order :: Cannot issue for \"*.*.leee.fun\": Domain name has more than one wildcard",
  "status": 400
}
[Sat Apr 11 09:41:55 CST 2020] Please check log file for more details: /volume1/system/syno-acme/acme.sh/acme.sh.log
[Sat Apr 11 09:41:56 CST 2020] Installing cert to:/usr/syno/etc/certificate/_archive/gRYk41/cert.pem
cat: /volume1/system/syno-acme/acme.sh/*.leee.fun/*.leee.fun.cer: No such file or directory
[ERR] fail to generateCrt
begin revert
begin revertCrt
/volume1/system/syno-acme/backup/20200411094143/certificate /usr/syno/etc/certificate
/volume1/system/syno-acme/backup/20200411094143/package_cert /usr/local/etc/certificate
begin reloadWebService
reloading new cert...
alias-register stop/waiting
relading Apache 2.2
pkg-apache22 stop/waiting
pkg-apache22 start/running, process 27370
done reloadWebService
done revertCrt

**Comment by andyzhshg** [comment]
@eiloogs 请问域名解析服务商是哪一个？DNSPod 目前版本会有问题，我发布了一个临时版本，可以暂时修复这个问题：

[https://github.com/andyzhshg/syno-acme/releases/tag/v0.2.1-dnspod](https://github.com/andyzhshg/syno-acme/releases/tag/v0.2.1-dnspod)

**Comment by eiloogs** [comment]
> @eiloogs请问域名解析服务商是哪个一个？DNSPod目前版本会有问题，我发布了一个临时版本，可以暂时修复这个问题：
> 
> https://github.com/andyzhshg/syno-acme/releases/tag/v0.2.1-dnspod

阿里云

**Comment by andyzhshg** [comment]
你的配置文件是不是有问题，在日志里看到：

```
[Sat Apr 11 09:41:53 CST 2020] Multi domain='DNS:.leee.fun,DNS:..leee.fun'
```

看起来是多了一个`.`。

正确的配置应该是：

```
export DOMAIN=leee.fun
```

**Comment by eiloogs** [comment]
> 你的配置文件是不是有问题，在日志里看到：
> 
> ```
> [Sat Apr 11 09:41:53 CST 2020] Multi domain='DNS:.leee.fun,DNS:..leee.fun'
> ```
> 
> 看起来是多了一个`.`。
> 
> 正确的配置应该是：
> 
> ```
> export DOMAIN=leee.fun
> ```

好的，问题解决，写根域名会自动申请通配符证书。感谢大佬！
