### ISSUE TITLE
DNSPOD更新失败

### ISSUE THREAD

**Issue by n0tva1id** [andyzhshg/syno-acme#48]
更新TXT记录时可以在DNSPOD上发现，但之后检查时提示
query timed out looking up TXT for _acme-challenge.xxxx.xxx
---
补充：
使用的是最新尝试解决DNSPOD问题的版本
已尝试设置3600秒sleep，在等待过程中尝试用本机手动dig _acme-challenge.xxxx.xx的txt记录，有正常返回文本。但最终验证失败
连续尝试过程中，中间有一次query timed out looking up CAA for _acme-challenge.xxxx.xxx

**Comment by RickGanKL** [comment]
这是个已知的问题。

**Comment by macooma** [comment]
参考https://myhloli.com/merlin-acme-sh.html， acme.sh有更新，但是这里指向的2.8.5是有问题的，需要更新至2.8.6

**Comment by andyzhshg** [comment]
已合并 @macooma 的PR至 2.8.6 版本的 acme.sh
