### ISSUE TITLE
不确写是不是证书脚本导致的

### ISSUE THREAD

**Issue by xzf158** [andyzhshg/syno-acme#6]
今天尝试使用你的脚本自动生成证书，我之前就有好几个证书，后来手动删除只保留一个证书，运行脚本后申请证书成功了，但后来就出现一个系统事件：由于 DSM 遭遇问题，无法正常启动。请联络 Synology 支持小组以获得帮助。排查了很久，没找到原因，不确定跟这个有没有关系？

**Comment by xzf158** [comment]
已经找到原因了，是web station导致的。

**Comment by PassWordE** [comment]
> 已经找到原因了，是web station导致的。

请问是怎么解决的？也碰到一样的问题了。。。很头疼现在
