### ISSUE TITLE
是否支持主域名的更新？

### ISSUE THREAD

**Issue by ZhaoqiangCn** [andyzhshg/syno-acme#7]
abc.com

**Comment by tayadwx** [comment]
add --d "${DOMAIN}" in line 49 and line 50:

line 49: 
${ACME_BIN_PATH}/acme.sh --issue --dns ${DNS} --dnssleep ${DNS_SLEEP} **-d "${DOMAIN}"** -d "*.${DOMAIN}"

line 50: 
${ACME_BIN_PATH}/acme.sh --installcert **-d ${DOMAIN}** -d *.${DOMAIN} \

**Comment by andyzhshg** [comment]
新版本已经添加主域名支持
[https://github.com/andyzhshg/syno-acme/releases/tag/v0.1.5](https://github.com/andyzhshg/syno-acme/releases/tag/v0.1.5)
