### ISSUE TITLE
FreeDNS使用脚本出错

### ISSUE THREAD

**Issue by redraiderj** [andyzhshg/syno-acme#8]
部分log如下：

begin generateCrt
begin updating default cert by acme.sh tool
[Tue Nov  6 01:52:46 CST 2018] Registering account
[Tue Nov  6 01:52:50 CST 2018] Registered
[Tue Nov  6 01:52:50 CST 2018] ACCOUNT_THUMBPRINT='k16lk8IV7fEFsc5mq_KiZ7fHcpcchgYGW8cJQLTdL28'
[Tue Nov  6 01:52:50 CST 2018] Creating domain key
[Tue Nov  6 01:52:50 CST 2018] The domain key is here: /volume3/homes/admin/syno-acme-0.1.4/acme.sh/*.dendrobium.ignorelist.com/*.dendrobium.ignorelist.com.key
[Tue Nov  6 01:52:50 CST 2018] Single domain='*.dendrobium.ignorelist.com'
[Tue Nov  6 01:52:50 CST 2018] Getting domain auth token for each domain
[Tue Nov  6 01:52:53 CST 2018] Getting webroot for domain='*.dendrobium.ignorelist.com'
[Tue Nov  6 01:52:53 CST 2018] Found domain api file: /volume3/homes/admin/syno-acme-0.1.4/acme.sh/dnsapi/dns_freedns.sh
[Tue Nov  6 01:52:53 CST 2018] Add TXT record using FreeDNS
[Tue Nov  6 01:52:59 CST 2018] FreeDNS failed to add TXT record for _acme-challenge.dendrobium as FreeDNS requested security code
[Tue Nov  6 01:52:59 CST 2018] Note that you cannot use automatic DNS validation for FreeDNS public domains
[Tue Nov  6 01:52:59 CST 2018] Error add txt for domain:_acme-challenge.dendrobium.ignorelist.com
[Tue Nov  6 01:52:59 CST 2018] Please add '--debug' or '--log' to check more details.
[Tue Nov  6 01:52:59 CST 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Tue Nov  6 01:53:01 CST 2018] Installing cert to:/usr/syno/etc/certificate/_archive/DASRiV/cert.pem
cat: /volume3/homes/admin/syno-acme-0.1.4/acme.sh/*.dendrobium.ignorelist.com/*.dendrobium.ignorelist.com.cer: No such file or directory
[Tue Nov  6 01:53:01 CST 2018] Installing key to:/usr/syno/etc/certificate/_archive/DASRiV/privkey.pem
[Tue Nov  6 01:53:01 CST 2018] Installing full chain to:/usr/syno/etc/certificate/_archive/DASRiV/fullchain.pem
cat: /volume3/homes/admin/syno-acme-0.1.4/acme.sh/*.dendrobium.ignorelist.com/fullchain.cer: No such file or directory
./cert-up.sh: line 54: cd: /volume3/homes/admin/syno-acme-0.1.4/temp/acme.sh-2.7.8: No such file or directory
done generateCrt

**Comment by andyzhshg** [comment]
默认的配置文件里没有freedns的配置项，需要自己加一下：
```
export FREEDNS_User=username
export FREEDNS_Password=password
```
如果加了还是不行的话，估计就得找acme.sh的原作者或者freedns来解决了，本项目只是一个自动调用脚本。

**Comment by redraiderj** [comment]
已经加了，不然会报auth错误，我再自己看看，不行只能去原作者那里了。
