### ISSUE TITLE
全新的DMS7.0，运行出现这个提示无法使用，需要再安装什么吗

### ISSUE THREAD

**Issue by jijinli777** [andyzhshg/syno-acme#83]
日志：Usage: /volume2/docker/syno-acme/cert-up.sh {update|revert}
apache,web station,python2都有安装了！也是这样~

**Comment by YuukiHibiki** [comment]
> 日志：Usage: /volume2/docker/syno-acme/cert-up.sh {update|revert} apache,web station,python2都有安装了！也是这样~

你好，请教一下你是如何解决的？
